### ISSUE TITLE
Cache control headers

### ISSUE THREAD

**Issue by qzminski** [terminal42/contao-assets#1]
I have created the first draft of the bundle, feel free to check it out. What I would like to add is the `max_age` cache control header of 1 year (maximum according to RFC). That would mean the browser would cache the file as long as possible and if the file would change, so would his filename version and thus the browser would download the new one.

Not sure how to do it best though, do we have to provide a custom route for this? Then we would also have to ensure that the dist files are not publicly accessible but only through this route.

@terminal42/pilots

**Comment by Toflar** [comment]
Looks good to me at first sight. Not sure if it's what @aschempp imagined, I think he should check for the concept. Regarding the headers, I think it would be a good idea to actually have a custom route for these assets to be able to set the headers. Of course it's always better to let the server handle the static files and not bother the php process for it. But to be honest, there are multiple advantages when we do it in php:

* it also works for any other webserver
* we can control it in the code so it's the same for all projects
* and anyway, it's cached for 1 year so the php process isn't hit very often anyway and even if it is, who the fuck cares anyway :D

**Comment by aschempp** [comment]
I dont know about this… it means we need to pipe *all* assets. It can cause issues with relative paths in CSS files. And the cache only applies for the same visitor, but if you have a lot of visitors you boot Symfony just to pipe a CSS file. To me caching is less relevant than that, and caching should be configured on the server. Like adding a default cache lifetime to our edition.

**Comment by qzminski** [comment]
Also what came to my mind is that it may not be possible to use stuff such as Apache/nginx modules that do e.g. compression, yet I am not sure about that – maybe they can also act on the app response and not static files only.

**Comment by qzminski** [comment]
I have added the appropriate note in the README file in 411505e.
